spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/analyticservice?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true