spring:
  data:
    mongodb:
      uri: mongodb://root:root@analytic-service-db-service:27017/analyticservice?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: "http://discoveryserverservice:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
