spring:
  data:
    mongodb:
      uri: mongodb://root:root@analytic-service-db:27017/analyticservice?authSource=admin

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: "http://discoveryserver:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
