spring:
  datasource:
    url: jdbc:mysql://billing-payment-service-db:3306/billingpaymentservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  metrics:
    export:
      prometheus:
        enabled: true

customer:
  service:
    url: "http://customerservice:8083"

plan:
  service:
    url: "http://planservice:8086"

eureka:
  client:
    service-url:
      defaultZone: "http://eurekaserver:8761/eureka"
    register-with-eureka: true
    fetch-registry: true