spring:
  datasource:
    url: jdbc:mysql://localhost:3307/contractservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true