spring:
  datasource:
    url: jdbc:mysql://contract-service-db-service:3307/contractservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkinservice:9411/api/v2/spans"
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: "http://eurekaserverservice:8761/eureka"
    register-with-eureka: true
    fetch-registry: true