spring:
  datasource:
    url: jdbc:postgresql://user-service-db-service:5435/userservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: "http://eurekaserverservice:8761/eureka"
    register-with-eureka: true
    fetch-registry: true